version: 0.2
phases:
  install:
    commands:
      - 'echo "Installing dependencies"'
      - 'yum update -y'
      - 'sudo yum groupinstall -y "Development Tools"'
      - 'sudo yum install -y libtool pkgconfig autoconf automake openssl-devel'
      - 'yum install -y --skip-broken bash-completion bzip2 file gcc gcc-c++ git-core make ncurses-devel patch rsync tar unzip wget which diffutils python3 python3-setuptools perl-base perl-Data-Dumper perl-File-Compare perl-File-Copy perl-FindBin perl-IPC-Cmd perl-JSON-PP perl-lib perl-Thread-Queue perl-Time-Piece'
  pre_build:
    commands:
      - 'echo "Cloning OpenWrt: ${OPENWRT_REF}"'
      - 'git clone https://git.openwrt.org/openwrt/openwrt.git'
      - 'cd openwrt'
      - 'git checkout "${OPENWRT_REF}"'
      - './scripts/feeds update -a'
      - './scripts/feeds install -a'
  build:
    commands:
      - echo "=== Generating .config for TARGET=${TARGET} SUBTARGET=${SUBTARGET} PROFILE=${PROFILE} ==="
      - wget https://downloads.openwrt.org/releases/24.10.2/targets/${TARGET}/${SUBTARGET}/config.buildinfo -o .config
      - mv config.buildinfo .config
      - make defconfig
      - 'echo "=== Starting build ==="'
      - 'make tools/{clean, compile}'
      - 'make tools/libressl/compile'
      - 'make -j1 V=sc download world'
      - 'echo "commit=${CODEBUILD_RESOLVED_SOURCE_VERSION}" > build-info.txt'
      - 'echo "openwrt_ref=${OPENWRT_REF}" >> build-info.txt'
      - 'echo "target=${TARGET}" >> build-info.txt'
      - 'echo "subtarget=${SUBTARGET}" >> build-info.txt'
      - 'echo "profile=${PROFILE}" >> build-info.txt'
      - 'echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> build-info.txt'
      - 'echo "Syncing to s3://${IMAGES_BUCKET}/openwrt/${OPENWRT_REF}/${TARGET}_${SUBTARGET}/${PROFILE}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/"'
      - 'aws s3 sync bin/ "s3://${IMAGES_BUCKET}/openwrt/${OPENWRT_REF}/${TARGET}_${SUBTARGET}/${PROFILE}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/" --delete'
artifacts:
  files:
    - 'openwrt/build-info.txt'
    - 'openwrt/bin/**/*'
  discard-paths: no
